### ISSUE TITLE
Fix css responsiv on Header

### ISSUE THREAD

**Issue by millbergm** [95joaols/webbshop-schoolAssignments-#73]
![Skärmbild 2021-09-09 120104](https://user-images.githubusercontent.com/71013225/132666058-4f10ef2f-ea6a-4de4-8ab0-c18a1461e4a9.jpg)

ser inte bra ut på liten skärm

**Comment by 95joaols** [comment]
jag tror att det är att bilderna i pudukterna är osaken.
Jag tror att vi får ändra ProductCardList att andvända sig av grid.
https://material-ui.com/components/grid/

**Comment by 95joaols** [comment]
nu när jag tittar på den tror jag att det är de 4 knappar som inte ändrar stolek

**Comment by RikardF** [comment]
Jajaja. Detaljer... :P

**Comment by millbergm** [comment]
![Skärmbild 2021-09-09 150128](https://user-images.githubusercontent.com/71013225/132690554-098d3c06-8a35-4065-ab7f-0b670a4c554d.jpg)

ett förslag på hur det kan se ut, funkar med knapparna men har fortfarande titeln som ligger bakom

**Comment by RikardF** [comment]
Snyggt! Krympa font sizen på titeln bara kanske?
